<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gasoek+One&family=Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800&display=swap" rel="stylesheet">
        <style>
            .logo-text {
                font-size: 24px;
                font-weight: 400;
                font-style: normal;
                letter-spacing: 1px;

                color: #002868;

                text-decoration: none;

                font-family: "Gasoek One", sans-serif;

                transition: 0.2s ease;
            }

            .logo-text:hover {
                color: #162d66;
            }

            .btn {
            background: #002868;
            color: white;
            padding: 8px 14px;
            border-radius: 6px;
        }

    </style>
</head>
<body>


    <nav class="d-flex justify-content-between align-items-center px-5 py-3 bg-white shadow-sm">
        <!-- <a href="/">
            <img src="/images/logo.png" 
                alt="Carolina Explorer"
                style="height:40px;">
        </a> -->
        <a href="/" class="logo-text">
            Carolina Explorer
        </a>
        

        <div>
            <a href="/guides/signup" class="me-3 text-dark text-decoration-none">
                Become a tour guide
            </a>
            <a href="/login" class="me-3 text-dark text-decoration-none">
                Log in
            </a>
            <a href="/signup" class="btn px-3">
                Sign Up
            </a>
        </div>
    </nav>



        
    </body>
</html>